DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS request;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_name varchar(64) NOT NULL,
  user_email varchar(128) NOT NULL,
  CONSTRAINT pk_users_user_id PRIMARY KEY (user_id),
  CONSTRAINT uk_users_user_email UNIQUE (user_email)
);

CREATE TABLE IF NOT EXISTS request (
  request_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  request_description varchar(3000) NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  user_id INTEGER NOT NULL,
  CONSTRAINT pk_request_request_id PRIMARY KEY (request_id),
  CONSTRAINT fk_request_user_id FOREIGN KEY (user_id)
            REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS item (
  item_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  item_name varchar(64) NOT NULL,
  item_description varchar(1024) NOT NULL,
  item_available boolean NOT NULL,
  user_id INTEGER NOT NULL,
  request_id INTEGER,
  CONSTRAINT pk_item_item_id PRIMARY KEY (item_id),
  CONSTRAINT fk_item_user_id FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
  CONSTRAINT fk_item_request_id FOREIGN KEY (request_id)
          REFERENCES request (request_id),
  CONSTRAINT ck_item_request_id CHECK (request_id > 0)
);

CREATE TABLE IF NOT EXISTS booking (
  booking_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  status VARCHAR(8) NOT NULL,
  CONSTRAINT pk_booking_booking_id PRIMARY KEY (booking_id),
  CONSTRAINT fk_booking_item_id FOREIGN KEY (item_id)
        REFERENCES item (item_id) ON DELETE CASCADE,
  CONSTRAINT fk_booking_user_id FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
  CONSTRAINT ck_booking_status CHECK (status IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS comments (
  comment_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text varchar(3000) NOT NULL,
  item_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT pk_comments_comment_id PRIMARY KEY (item_id),
  CONSTRAINT fk_comments_item_id FOREIGN KEY (item_id)
          REFERENCES item (item_id) ON DELETE CASCADE,
  CONSTRAINT fk_comments_user_id FOREIGN KEY (user_id)
          REFERENCES users (user_id) ON DELETE CASCADE
);